### ISSUE TITLE
No beams can be drawn with prompt saying more information is required

### ISSUE THREAD

**Issue by fantacyboy** [LeoBelmont/Structures-Explained#1]
Hello LeoBelmont

When I try to generate the beam element via UI window, it prompts that more information is required. It seems that it skips the lines of if-else, and goes strainght to the line of except. Could you please help to sort it out?

Kind Regards

Caer

    def add_beam(self):
        try:
            self.workaround()
            e = self.mw.elementtype.currentIndex()

            if self.mw.utilizeinfo.isChecked():
                EI = float(self.fn.filter(self.mw.beam_E.text())) * float(self.fn.filter(self.mw.beam_I.text()))
                EA = float(self.fn.filter(self.mw.beam_E.text())) * float(self.fn.filter(self.mw.beam_A.text()))
                element_types = ["beam", "truss"]
                self.ss.add_element(
                    location=[[float(self.fn.filter(self.mw.beam_x1.text())),
                               float(self.fn.filter(self.mw.beam_y1.text()))],
                              [float(self.fn.filter(self.mw.beam_x2.text())),
                               float(self.fn.filter(self.mw.beam_y2.text()))]],
                    EI=EI, EA=EA, element_type=element_types[e])

            else:
                self.ss.add_element(
                    location=[[float(self.fn.filter(self.mw.beam_x1.text())),
                               float(self.fn.filter(self.mw.beam_y1.text()))],
                              [float(self.fn.filter(self.mw.beam_x2.text())),
                               float(self.fn.filter(self.mw.beam_y2.text()))]])

            self.visualize_structure()
            self.states.append(pickle.dumps(self.ss))
        except:
            self.fn.warning()

**Comment by LeoBelmont** [comment]
Hello fantacyboy!

Thank you for reporting your issue.

That is likely due to an incompatible anaStruct. Are you using my fork of anaStruct? If so you might want to try the master instead of the sx-legacy branch.

Fork available here: https://github.com/LeoBelmont/anaStruct/

Let me know if that works!

**Comment by fantacyboy** [comment]
Hello LeoBelmount

I followed the instructions to install the one from sx-legacy branch at the very beginning. Then the error info of "cannot import name 'functions' from 'StructuresExplained.solutions' (unknown location) " prompted, which didn't happen with other versions. Therefore I tried the master one for anastruct, and luckily I can run the examples in anastruct standalone without any problems  However when I tried to use the UI interface of StructuresExplained to run the simple beam structure after I picked two points in the screen and clicked the button, I found the prompted window saying " more information is required" which I mentioned to you yesterday.

Thanks for your response. 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\anastruct-1.1.1-py3.10.egg\anastruct\__init__.py", line 1, in <module>
    from anastruct.fem.system import SystemElements
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\anastruct-1.1.1-py3.10.egg\anastruct\fem\system.py", line 4, in <module>
    from anastruct.fem.postprocess import SystemLevel as post_sl
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\anastruct-1.1.1-py3.10.egg\anastruct\fem\postprocess.py", line 4, in <module>
    from StructuresExplained.solutions import functions
ImportError: cannot import name 'functions' from 'StructuresExplained.solutions' (unknown location)

**Comment by LeoBelmont** [comment]
I've updated my anaStruct fork. It should work for you now.

I've also updated the install instructions since the sx-legacy branch is no longer the correct branch to use.

Please let me know if it works for you now and if you run into any more issues. Thank you!

**Comment by fantacyboy** [comment]
Hello LeoBelmount

Cheers for the latest updating, and it's now compatible. Superb.
